#!/usr/bin/perl -w
#
# Copyright (C) 2004 - 2014  Jon Stockill, Martin Spott
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

use Cwd;
use DBI;
use File::Path;
use MIME::Base64;
use strict;

local($/) = undef;
my $basedir = getcwd;
my $Count = 0;
#my $DEBUG = 1;
my ($dbh, $sth, %row);

my $pghost=$ENV{"PGHOST"};
my $pgdatabase=$ENV{"PGDATABASE"};

# Make STDOUT "hot"
select((select(STDOUT), $|=1)[0]);

$dbh = (DBI->connect("DBI:Pg:host=$pghost;dbname=$pgdatabase", "webuser", ""));

#print STDOUT "Executing query to export shared models...\n" if $DEBUG == 1;
$dbh = get_dbh() unless $dbh;
$sth = $dbh->prepare("SELECT mo_id, concat('/Models/', mg_path) AS path, LENGTH(mo_modelfile) AS mo_size, mo_modelfile, mg_path FROM fgs_models, fgs_modelgroups WHERE mo_shared > 0 AND mo_shared = mg_id ORDER BY fgs_modelgroups.mg_id, fgs_models.mo_id;");
$sth->execute() or die $dbh->errstr;

#print STDOUT "done\n" if $DEBUG == 1;
$sth->bind_columns( \( @row{ @{$sth->{NAME_lc} } } ));

while ($sth->fetchrow_arrayref) {
#    print STDOUT "Exported " . $Count++ . " models\r" if $DEBUG == 1;

    if ($row{mo_size} > 15)
    {	
        my $modeldata = decode_base64($row{mo_modelfile});
#        print STDOUT $row{mo_id} . " " . $row{path} . "\n" if $DEBUG == 1;
        my $mgpath = $basedir . $row{path};
        chdir $mgpath;
        open(BUFF, "| tar xfz -");
        print BUFF $modeldata;
    }
    else
    {
        print STDOUT "WARNING: " . $row{path} . " is not in the database\n";
    };
};
print STDOUT "Models done\n";

exit(0);

# EOF
