#!/bin/bash
#
# Copyright (C) 2004 - 2014  Jon Stockill, Martin Spott
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

cd `dirname ${0}` && export BASEDIR=`pwd`
#
sourcedir=${BASEDIR}/Objects
destdir=${HOME}/scenemodels/download

# Start above 'Objects' and add 'Objects' to the path in the downloadable
# files; Martin, 2008-10-03
cd ${sourcedir}
for PACKFILE in [ew][0-9][0-9]0[ns][0-9]0
do
#	echo "Packing ${PACKFILE}"
	cd ${sourcedir}/.. && tar cfz ${destdir}/${PACKFILE}\.tgz --owner=root --group=root Objects/${PACKFILE}
done
cd ${sourcedir}/.. && tar cfz ${destdir}/GlobalObjects.tgz --owner=root --group=root Objects/*

# EOF
